name: Supabase keepalive
on:
  schedule:
    - cron: '0 10 */3 * *' # every 3 days at 10:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          : "${SUPABASE_URL:?missing} ${SUPABASE_KEY:?missing}"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY || secrets.SUPABASE_ANON_KEY }}

      - name: Ensure row exists (UPSERT id=1)
        run: |
          set -euo pipefail
          NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          NOTE="init-$(openssl rand -hex 6)"

          curl -sS -i -X POST "$SUPABASE_URL/rest/v1/keepalive?on_conflict=id" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            -H "Content-Type: application/json" \
            -H "Prefer: resolution=merge-duplicates,return=representation" \
            --data "{\"id\":1,\"touched_at\":\"$NOW\",\"note\":\"$NOTE\"}" | sed -n '1,40p'
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY || secrets.SUPABASE_ANON_KEY }}

      - name: Touch keepalive row (PATCH with random note)
        run: |
          set -euo pipefail
          NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          NOTE="run-$NOW-$(openssl rand -hex 6)"

          curl -sS -i -X PATCH "$SUPABASE_URL/rest/v1/keepalive?id=eq.1" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=representation" \
            --data "{\"touched_at\":\"$NOW\",\"note\":\"$NOTE\"}" | sed -n '1,120p'
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY || secrets.SUPABASE_ANON_KEY }}

      - name: Verify update (GET the row)
        run: |
          set -euo pipefail
          echo "Reading back supabase keepalive row:"
          curl -sS "$SUPABASE_URL/rest/v1/keepalive?id=eq.1&select=id,touched_at,note" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            -H "Accept: application/json" | jq .
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY || secrets.SUPABASE_ANON_KEY }}
